[features]
seeds = false
[programs.localnet]
clever_todo = "FHi9b593PHHVjcrvRBXjAmRd6JsHkWCoLmC8CHdkDUy3"

[programs.devnet]
clever_todo = "FHi9b593PHHVjcrvRBXjAmRd6JsHkWCoLmC8CHdkDUy3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/john/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
